# Zenith Hyprland Configuration

# Environment & Autostart
exec-once = dbus-update-activation-environment --all --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start hyprland-session.target
exec-once = systemctl --user restart xdg-desktop-portal-hyprland xdg-desktop-portal
exec-once = quickshell -d
exec-once = hyprlock &
exec-once = wl-clip-persist --clipboard both &
exec-once = wl-paste --watch cliphist store &
exec-once = hyprctl setcursor Bibata-Modern-Ice 24 &

# Load Hyprland Lua Configuration
source = ~/.config/hypr/hyprland.lua
