swipe:
  3:
    left:
      sendkey: "PREVIOUSSONG"
    right:
      sendkey: "NEXTSONG"
    up:
      sendkey: "volumeup"
    down:
      sendkey: "volumedown"
  4:
    up:
      sendkey: "F5"
    down:
      sendkey: "F6"
hold:
  3:
    sendkey: "PLAYPAUSE"
pinch:
  in:
    sendkey: "PLAYPAUSE"
threshold:
  pinch: 1
  hold: 0

interval:
  swipe: 1
  pinch: 1
  hold: 0.5
