backend = "fastresize"
color_space = "lch"
# dark - harddark - softdark
palette = "dark"
# Ensures a "readable contrast" (OPTIONAL, disabled by default)
check_contrast = true
saturation = 120
# alpha = 100
lighten= 60
threshold = 20

[templates]

[templates.ironbar]
template = 'ironbar.template.toml'
target   = '/home/zaeem/.config/ironbar/ironbar_dynamic_colors.css'


